modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="slabstoblocks_create"
version="${file.jarVersion}"
displayName="Slabs to Blocks: Create"
logoFile="SlabstoBlocks_Create_Icon.png"
credits="Idea for this mod was inspired from the original Slabs to Blocks by Mars" 
authors="LneedhelpnowPLS"
description='''
Adds crafting recipes for making Create's copper slabs into their block variants.
'''
[[dependencies.slabstoblocks_create]] 
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.slabstoblocks_create]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"