modLoader="javafml"
loaderVersion="[43,)" This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]]
modId="slabstoblocks_create"
version="${file.jarVersion}"
displayName="Slabs to Blocks: Create"
logoFile="examplemod.png" 
credits="Idea for this mod was inspired from the original Slabs to Blocks by Mars" 
authors="LneedhelpnowPLS"
description='''
Adds crafting recipes for making Creates's copper slabs into their block variants.
'''
[[dependencies.slabstoblocks_create]] 
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.slabstoblocks_create]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"